const menu = [
  {
    id: 1,
    title: 'Maple Dream',
    category: 'breakfast',
    price: 8.59,
    img: './images/item-1.jpg',
    desc: `Cupcake ipsum dolor sit amet marshmallow brownie. Chocolate cake jelly-o cake icing apple pie lollipop gummies. Croissant pudding gummies I love I love fruitcake. `,
  },
  {
    id: 2,
    title: 'Chicken revenge',
    category: 'lunch',
    price: 12.99,
    img: './images/item-2.jpg',
    desc: `Candy caramels gingerbread I love tart cake cake. Toffee tiramisu I love icing chupa chups. Biscuit lemon drops I love marshmallow gingerbread wafer jelly-o biscuit. `,
  },
  {
    id: 3,
    title: 'Angel’s Milk',
    category: 'shakes',
    price: 5.49,
    img: './images/item-3.jpg',
    desc: `Jelly-o oat cake pastry chupa chups lollipop chocolate. Tart I love biscuit sweet soufflé. Fruitcake I love I love jujubes macaroon soufflé shortbread croissant.`,
  },
  {
    id: 4,
    title: 'Hangover kickstart',
    category: 'breakfast',
    price: 9.99,
    img: './images/item-4.jpg',
    desc: `Bonbon pie tiramisu gummies chocolate cake gingerbread. Carrot cake muffin dragée jelly-o jelly-o. Shortbread carrot cake tiramisu marshmallow gingerbread cake. `,
  },
  {
    id: 5,
    title: 'Italian dream',
    category: 'lunch',
    price: 18.2,
    img: './images/item-5.jpg',
    desc: `I love sweet cupcake I love marzipan. Chocolate cake chocolate cookie halvah I love sesame snaps. Jelly-o icing biscuit jelly pie. `,
  },
  {
    id: 6,
    title: 'Heaven In A Cup',
    category: 'shakes',
    price: 10.99,
    img: './images/item-6.jpeg',
    desc: `Fruitcake tart jujubes tootsie roll ice cream I love jujubes. Donut gingerbread I love donut lollipop. Marzipan tootsie roll wafer I love chocolate cake cookie danish jelly-o cookie.`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 7.99,
    img: './images/item-7.jpg',
    desc: `Fruitcake tart brownie I love sugar plum biscuit jujubes. Sweet jelly beans dessert bonbon sugar plum fruitcake danish pudding.`,
  },
  {
    id: 8,
    title: 'Buffalo Bill',
    category: 'lunch',
    price: 14.6,
    img: './images/item-8.jpg',
    desc: `Cupcake ipsum dolor sit amet dessert fruitcake. I love tiramisu liquorice jelly beans I love bear claw biscuit apple pie. Icing tootsie roll jelly lemon drops I love.`,
  },
  {
    id: 9,
    title: 'Kisses that Kill',
    category: 'shakes',
    price: 7.54,
    img: './images/item-9.jpg',
    desc: `Cupcake ipsum dolor sit amet soufflé muffin. Cookie I love jelly candy canes croissant cake. Topping pastry cotton candy cheesecake croissant.`,
  },
  {
    id: 10,
    title: 'Pizza Margarita',
    category: 'lunch',
    price: 14.11,
    img: './images/item-10.jpg',
    desc: `Cupcake ipsum dolor sit amet soufflé muffin. Cookie I love jelly candy canes croissant cake. Topping pastry cotton candy cheesecake croissant.`,
  },
]
export default menu
